/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.41).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package br.com.orders.api;

import br.com.orders.model.Cliente;
import br.com.orders.model.Produto;
import io.swagger.annotations.Api;
import org.springframework.web.bind.annotation.GetMapping;

import java.util.List;

@Api(value = "MockyApi")
public interface MockyApi {

    @GetMapping(value = "/45e7bcac-6f2c-40f1-8662-eb3a62aa005c")
    List<Produto> getProdutos();

    @GetMapping(value = "/d1992fa3-e01d-43ea-97d6-e8ef302c886d")
    List<Cliente> getClientes();

}

